### ISSUE TITLE
Upgrade compatibility with Vite 5

### ISSUE THREAD

**Issue by nilshelmig** [solidjs/vite-plugin-solid#126]
[Vite 5 got released](https://vitejs.dev/blog/announcing-vite5) and this plugin is missing compatibility with the version 5.

From first look, it seems like everything should work with version 5 and only the peer dependency needs to be added. For more information there is the [migration guide](https://vitejs.dev/guide/migration)

**Comment by nilshelmig** [comment]
Possibly relates to https://github.com/solidjs/solid-start/issues/1123

**Comment by codylindley** [comment]
This will work until then in your package.json

```
...
    "overrides": {
        "vite-plugin-solid": {
            "vite": "^5.0.0"
        }
    },
...
```
