### ISSUE TITLE
feature: support custom options for babel-preset-solid

### ISSUE THREAD

**Issue by zhaoyao91** [solidjs/vite-plugin-solid#13]
we need to pass in some other options for babel-preset-solid, by searching the code I didn't find a way to give these options.

(I want to pass in `"delegateEvents": false`)

**Comment by amoutonbrady** [comment]
Hey, that's a good idea. I guess I wanted to make the plugin as lean as possible, but I've come to realize that it might not be the best approach as Solid in general is for people that likes to tinker with configuration and fine tune it to their needs.

This should be fixed. I added a `solid` option that takes the same options as [babel-plugin-jsx-dom-expressions](https://github.com/ryansolid/dom-expressions/tree/main/packages/babel-plugin-jsx-dom-expressions#plugin-options).

There might be some overriding to take care of later on but that should fix your issue for now on :)

Let me know if it works as intended.
