### ISSUE TITLE
missing changelog / release tags

### ISSUE THREAD

**Issue by birkskyum** [solidjs/vite-plugin-solid#143]
i know it's a bit pedantic, but it would be helpful if releases got a changelog and a github tag/release.

last changelog entry / github release was 2.3.0 (2022-07-14)

it's i.e. convenient if dependabot can pull the release notes

**Comment by ryansolid** [comment]
Yeah @amoutonbrady did a great job. I've added changesets. We will be using them from now on. I will try to remember to tag releases as well.
