### ISSUE TITLE
Unable to pass signal to child components

### ISSUE THREAD

**Issue by thep0y** [solidjs/vite-plugin-solid#146]
### Describe the bug

When `signal` is passed to a child component, an error is thrown: `Uncaught ReferenceError: props is not defined`, even though `props` contains other static properties. Printing `props` in the console shows that `props` is not defined, even though static properties exist within it.

This bug appeared after updating the dependencies; it did not exist before:

```
solid-js 1.8.12 -> 1.8.14
vite 5.0.12 -> 5.1.1
vite-plugin-solid 2.9.1 -> 2.10.0
```

After updating the dependencies, none of the components I wrote that require signal to be passed can render correctly, causing the entire program to fail to run.

After downgrading `vite-plugin-solid` to `2.9.1`, this bug no longer exists.

### Your Example Website or App

https://github.com/thep0y/solid-demo

### Steps to Reproduce the Bug or Issue

1. `pnpm i`
2. `pnpm dev`

### Expected behavior

As the title says, `signal` should be passed to the child component as a property, just like before.

### Screenshots or Videos

<img width="549" alt="截屏2024-02-14 16 58 33" src="https://github.com/solidjs/solid/assets/51874567/6eb82e71-b238-4ea0-9a84-6a36b3972c1e">
<img width="736" alt="截屏2024-02-14 16 59 02" src="https://github.com/solidjs/solid/assets/51874567/67fac0f8-b53c-4514-9536-ec02d2cb4a6e">

### Platform

- OS: macOS
- Browser: Chrome, Safari
- Version: latest

**Comment by oddcelot** [comment]
Just upgraded also `vite-plugin-solid` to `2.10.0` and I'm seeing the same error in `For` when iterating over a static array.
I was thinking this might be just as HMR issue because of https://github.com/solidjs/vite-plugin-solid/commit/c6bb7ac0b85062a50e8b1fafd8796e073fef1aec but it seems that this is also throwing after running the built application.

I'm not sure whether this issue https://github.com/solidjs/solid/issues/2070 should be removed, since this seems more related to the vite plugin.

**Comment by asabatba** [comment]
In my case it's causing issues with Context/Provider.
In an app that was working fine, context is now always undefined.

**Comment by ryansolid** [comment]
FYI I reverted the Refresh update for now in 2.10.1 but I'm keeping this issue so we can debug it.

**Comment by lxsmnsyc** [comment]
Related to https://github.com/solidjs/solid-refresh/issues/59

@ryansolid we can move this to Refresh

**Comment by ryansolid** [comment]
Yeah this should be fixed now. We are still testing next version with new refresh.
