### ISSUE TITLE
Breaking updating from v2.9.1 from v2.10.0

### ISSUE THREAD

**Issue by codylindley** [solidjs/vite-plugin-solid#147]
When updating this package our solidjs application is throwing an error from somewhere. Seems to have something to do with `props`. We are still trying to track the error down. 

Is anyone else seeing their application go from working to not working based only on this package version change?

I am asking here because I am trying to understand if we are the only ones seeing a breaking change like this, which would indicate that we are doing something that is no longer failing silently maybe.

**Comment by dested** [comment]
I am getting it with 


```typescript
export const SceneComponent = <T extends any>(
  props: {
    keepKey: string;
    onSceneReady: (scene: Scene) => T;
    onRender?: (scene: Scene, state: T) => void;
  } & ComponentProps<'canvas'>
) => {
```
onRender

'Transform failed with 1 error:\ndirectionalDisplay.tsx:123:19: ERROR: Expected ")" but found ":"'
