### ISSUE TITLE
Does this plugin support sourcemaps?

### ISSUE THREAD

**Issue by kirkedev** [solidjs/vite-plugin-solid#21]
Hello,

I'm getting sourcemaps for all of my code except the tsx files. Wondering if I'm doing something wrong, or if this just isn't supported (yet?).

**Comment by amoutonbrady** [comment]
Theoratically, we should expose sourcemaps for tsx / jsx files as per https://github.com/solidjs/vite-plugin-solid/blob/master/src/index.ts#L332

Let me see if I can reproduce on my side.

**Comment by amoutonbrady** [comment]
I would say it partially work. Not sure if that's the intended behavior or not but I definitely get the origin from the origin file as seen per this "Maps" logs

![image](https://user-images.githubusercontent.com/17355226/140415996-d2ffaf9b-d06f-4028-9749-9c5290b5bc4f.png)

However, the mapping is done to the compiled file. There's probably something better that we can do about it

**Comment by amoutonbrady** [comment]
I've managed to find the issue, there was some missing parameters in the babel config.
Do give it a try an let me know if things work better now :)

**Comment by kirkedev** [comment]
Works great! Thanks so much!
