### ISSUE TITLE
No HMR in vite

### ISSUE THREAD

**Issue by 314857493** [solidjs/vite-plugin-solid#30]
I use `npx degit solidjs/templates/js test-solod` to create project.
When I change App.jsx and save, the page did not change.
I saw the source in dev tool. I found there is a new file which name is `App.jsx?import&t=1645499368287`, but the page did not change with the file.

Here is the tmpl in `App.jsx?import&t=1645499368287`
```js
const _tmpl$ = _$template(`<div><header><img alt="logo"><p>Edit <code>src/App.jsx</code></p></header></div>`, 9);
```

But the page is still like
```js
const _tmpl$ = _$template(`<div><header><img alt="logo"><p>Edit <code>src/App.jsx</code> and save to reload.</p><a href="https://github.com/solidjs/solid" target="_blank" rel="noopener noreferrer">Learn Solid</a></header></div>`, 11);
```

**Comment by chandotnet** [comment]
I also got the issue with the JS template. Maybe related to the JS template only ? I have tried the TS template with bootstrap and hmr is working as expected.

**Comment by 314857493** [comment]
> I also got the issue with the JS template. Maybe related to the JS template only ? I have tried the TS template with bootstrap and hmr is working as expected.

yes, hmr is working is TS template, I changed the tsx file to jsx file, the hmr is also working. Maybe the JS template have something wrong.
