### ISSUE TITLE
`Could not find a declaration file` when setting package type to module

### ISSUE THREAD

**Issue by lomirus** [solidjs/vite-plugin-solid#32]
My `vite.config.ts`:
```ts
import { defineConfig } from 'vite';
import solidPlugin from 'vite-plugin-solid';
import { fileURLToPath } from 'url';
import { dirname } from 'path';

export default defineConfig({
  plugins: [solidPlugin()],
  build: {
    target: 'esnext',
    polyfillDynamicImport: false,
  },
  base: './',
  resolve: {
    alias: {
      "@": `${dirname(fileURLToPath(import.meta.url))}/src`
    }
  }
});
```
And the VSCode shows the error message below at the 2nd line:

> Could not find a declaration file for module 'vite-plugin-solid'. '/home/lomirus/cyl-centennial/node_modules/.pnpm/vite-plugin-solid@2.2.6/node_modules/vite-plugin-solid/dist/esm/index.mjs' implicitly has an 'any' type.
>  Try `npm i --save-dev @types/vite-plugin-solid` if it exists or add a new declaration (.d.ts) file containing `declare module 'vite-plugin-solid';`

While other packages do not show such error.

Once I change the `moduleResolution` to `node` in `tsconfig.json` and delete the `type` option in `package.json`, it would okay without error messages, but I just cannot figure it out why.

Now some other configurations below:

`tsconfig.json`:
```json
{
  "compilerOptions": {
    "strict": true,
    "target": "ESNext",
    "module": "ESNext",
    "moduleResolution": "nodenext",
    "allowSyntheticDefaultImports": true,
    "esModuleInterop": true,
    "jsx": "preserve",
    "jsxImportSource": "solid-js",
    "types": ["vite/client"],
    "noEmit": true,
    "isolatedModules": true,
    "paths": {
      "@/*": ["./src/*"]
    }
  }
}
```
`package.json`
```json
{
  "name": "cyl-centennial",
  "version": "0.0.0",
  "description": "",
  "private": true,
  "type": "module",
  "scripts": {
    "start": "vite",
    "dev": "vite",
    "build": "vite build",
    "serve": "vite preview"
  },
  "devDependencies": {
    "@types/node": "^17.0.23",
    "typescript": "^4.6.3",
    "vite": "^2.8.6",
    "vite-plugin-solid": "^2.2.6"
  },
  "dependencies": {
    "solid-app-router": "^0.3.2",
    "solid-js": "^1.3.13"
  }
}
```

**Comment by amoutonbrady** [comment]
Hey, sorry for the delayed answer.

I tried to reproduce your issue but couldn't unfortunately.
Here's a small reproduction of what you described: https://stackblitz.com/edit/vitejs-vite-mdytqw?file=package.json

Are you able to reproduce on stackblitz?

**Comment by lomirus** [comment]
@amoutonbrady Here is my [example](https://stackblitz.com/edit/vitejs-vite-dekbzb?file=vite.config.ts) which sets the `moduleResolution` to `nodenext` compared to yours. I am not sure if I can make such configurations at the same time (if not, maybe just it's my fault instead a bug):
```json
{
    "module": "ESNext",
    "moduleResolution": "nodenext",
}
```
But in my local VSCode environment, all the other packages work fine without errors:

![](https://i.imgur.com/Jk3kz5R.png)

`vite` and `lodash` are all ok here
