### ISSUE TITLE
No HMR in vite

### ISSUE THREAD

**Issue by vic1707** [solidjs/vite-plugin-solid#42]
#30 was closed by author but I have the same problem

Hello, HMR doesn't seems to work on my project nor on the JS, TS nor the TS-SASS templates 🤔 
I tried all 3 templates with this simple component
```ts
import { Component, createSignal } from 'solid-js';

export const Counter: Component = () => {
  const [count, setCount] = createSignal(0);

  return (
    <div class="counter">
      <p>
        <button type="button" onClick={() => setCount((c) => c + 1)}>
          count is: {count()}
        </button>
      </p>
    </div>
  );
};
```
the state is always reseted
the dependencies from my project
```
    "solid-js": "^1.4.5",
// devs
    "sass": "^1.53.0",
    "typescript": "^4.7.4",
    "vite": "^2.9.13",
    "vite-plugin-solid": "^2.2.6"
```

did I do something wrong?

**Comment by LXSMNSYC** [comment]
This is expected, specially if you're editing the Counter component.

**Comment by vic1707** [comment]
Event when I edit the main app component, why is it expected? Works well in react

**Comment by LXSMNSYC** [comment]
React has a completely different way of preserving state by utilizing their own architecture (Fiber). Solid doesn't have that kind of architecture (No VDOM, no hooks).

**Comment by St3Ko** [comment]
@lxsmnsyc does this also concern stores? For example i have an array of list items inside a store which get's set at runtime via API request (so the default is an empty array) and list them with the `List` component. When i now change the component, for example the `class` attribute from `flex` to `flex another-tailwind-class` the store gets reset and my items disappear.

```tsx
import {For} from "solid-js";
import {cartStore} from "@stores"
import {Button} from "@components/ui"

import type {Component} from "solid-js"

const Overview: Component = () => {
  const recipes = () => cartStore.cart_recipes
  return (
    <div>
      <div>Overview:</div>
      <For each={recipes()}>
        {(recipe) => <div>{recipe.recipe_id}: {recipe.servings}</div>}
      </For>
      <div class="flex">
        <Button size="small">do something</Button>
        <Button size="small">do something different</Button>
      </div>
    </div>
  )
}

export default Overview
```

**Comment by ryansolid** [comment]
It depends where the store is. Generally though we have no state preservation below the point of change currently. If you are seeing reloading in these cases it is work as far as we expect it to today.

**Comment by stabildev** [comment]
Is it possible to change that behavior? I added 
```
if (import.meta.hot) {
  import.meta.hot.accept()
  import.meta.hot.dispose(dispose)
}
```
to `index.jsx` but state is still lost on every change/file save.
