### ISSUE TITLE
Integration issue with vitest + WallabyJS

### ISSUE THREAD

**Issue by tslocke** [solidjs/vite-plugin-solid#45]
WallabyJS (test runner) has found a need to monkey-patch vite-plugin-solid to work around a bug. Might be something you want to fix.

Please see:

https://github.com/wallabyjs/public/issues/3030#issuecomment-1182596155

**Comment by ryansolid** [comment]
I believe the url with query string problem was solved by this PR: https://github.com/solidjs/vite-plugin-solid/pull/52
