### ISSUE TITLE
Unhandled Promise Rejection: ReferenceError: Can't find variable: React when updating to `2.3.3`

### ISSUE THREAD

**Issue by goenning** [solidjs/vite-plugin-solid#55]
Everything works fine on 2.3.2, but when I update the 2.3.3, it fails on this like:
```
render(() => <App />, document.getElementById("root") as HTMLElement);
```

The error is: `Unhandled Promise Rejection: ReferenceError: Can't find variable: React`

I'm using:
```
    "vite": "3.1.2",
    "solid-js": "^1.5.5",
```

**Comment by dnguyenlearning** [comment]
> Everything works fine on 2.3.2, but when I update the 2.3.3, it fails on this like:
> 
> ```
> render(() => <App />, document.getElementById("root") as HTMLElement);
> ```
> 
> The error is: `Unhandled Promise Rejection: ReferenceError: Can't find variable: React`
> 
> I'm using:
> 
> ```
>     "vite": "3.1.2",
>     "solid-js": "^1.5.5",
> ```

is there anyway to solve this?

**Comment by vsviridov** [comment]
Same issue here. With the previous version I get function calls like this:
```ts
import { createComponent as _$createComponent } from "/node_modules/.vite/deps/solid-js_web.js?v=3ad66bd1";
...
return _$createComponent(GlobalStyles, {
```
 but with 2.3.6 I get following in the same component:
```ts
// no explicit import
...
return React.createElement(GlobalStyles_default, {
```

so it's clear that the JSX is being processed differently.

**Comment by ryansolid** [comment]
Sorry didn't follow up with this but this issue should have been fixed over month ago. I think 2.3.8 onward..If anyone is still experiencing this let me know.
