### ISSUE TITLE
2.3.7 revert breaking solid-query package

### ISSUE THREAD

**Issue by ardeora** [solidjs/vite-plugin-solid#57]
Hello!

I see that the changes brought up in v2.3.6 were reverted back in 2.3.7. As we are trying to push a release for TanStack/solid-query this new version breaks things for the package where we get `React is undefined` errors. This was fixed in 2.3.6 but broke again in 2.3.7. Any idea why this was reverted? :D Maybe we are building the package incorrectly? Any tips on how to proceed further?

I would love to help out more but my knowledge with vite plugins is very limited

Thanks,
Aryan

**Comment by ryansolid** [comment]
I got a bunch of reports of that exact error in 2.3.6 and they said they needed to lock at 2.3.4. This was supposed to fix that. By removing the .jsx and .tsx like we did previously it was supposed to not send the JSX to the optimizer which means ESBuild shouldn't be getting it which should avoid the error.

Are you exporting JSX without a JSX extension. That's the only reason I can think of it getting to ESBuild.

**Comment by ryansolid** [comment]
Alright.. That's interesting. 2.3.6 happened to be the only version we've ever released that would have worked for the way the library is configured. Generally "solid" field expects a .jsx extension if it contains JSX. I think I have a middleground fix. But ultimately this is an issue I need to take up with Vite. There is just weirdness going on that is forcing us to jump through these hoops.

**Comment by ardeora** [comment]
Thank you so much for the comprehensive explanation here. Now I know what is going wrong 😅  I'll push for a new release that follows the best practice here by exporting index.jsx. Thanks again for jumping on it so fast.

**Comment by ardeora** [comment]
v2.3.8 indeed fixed the issue. I will close this issue for now. Thanks again
