### ISSUE TITLE
Vite3 globalThis._$HY is undefined

### ISSUE THREAD

**Issue by malekim** [solidjs/vite-plugin-solid#69]
I'm facing an issue after moving from vite2 to vite3 with SSR setup.

The error is:
```
globalThis._$HY is undefined
```

The repository to reproduce is here:
https://github.com/malekim/solidjs-fastify-ssr-template/tree/vite3

When you downgrade vite to 2.9.9 in package.json, everything starts to work.

**Comment by colmugx** [comment]
Same..
I got a error is `Cannot read properties of undefined (reading 'completed')`

"vite": "^3.2.4",
"vite-plugin-solid": "^2.4.0"

**Comment by colmugx** [comment]
> Same.. I got a error is `Cannot read properties of undefined (reading 'completed')`
> 
> "vite": "^3.2.4", "vite-plugin-solid": "^2.4.0"

well, maybe i lost `HydrationScript`

**Comment by almahdi404** [comment]
Did you find any solution?

I am also getting this error in with webpack.

**Comment by almahdi404** [comment]
I don't why but

```javascript
hydrate(() => <App />, document.getElementById("root")) // Doesn't work

render(() => <App />, document.getElementById("root"), { hydrate: true }) // Works
```

**Comment by ivanesik** [comment]
I guess a hydration script needs to be added. This script sets the initial value for _$HY

https://www.solidjs.com/guides/server#hydration-script
