### ISSUE TITLE
The route cannot be switched when vite4 is upgraded

### ISSUE THREAD

**Issue by beilo** [solidjs/vite-plugin-solid#79]
step1
npx degit solidjs/templates/ts-router my-solid-project

step2
"vite": "^3.0.9", 
->
"vite": "^4",

step3
pnpm i

step4
pnpm dev

step5
Click on the About button

result
The page doesn't change

**Comment by Manviel** [comment]
Same here https://github.com/solidjs/vite-plugin-solid/issues/78

**Comment by beilo** [comment]
```
"devDependencies": {
    "vite": "^4.0.3",
    "vite-plugin-solid": "^2.5.0",
    "vite-plugin-windicss": "^1.8.10"
  },
  "dependencies": {
    "@solidjs/router": "^0.6.0",
    "solid-js": "^1.6.6"
  }
```
"vite": "^4.0.3" It's normal。
thank you
