### ISSUE TITLE
Ambiguous `babel-preset-solid` dependency

### ISSUE THREAD

**Issue by rtritto** [solidjs/vite-plugin-solid#88]
From [Installation](https://github.com/solidjs/vite-plugin-solid#installation) section in README:
> Install `vite`, `vite-plugin-solid` and `babel-preset-solid` as dev dependencies.

[package.json](https://github.com/solidjs/vite-plugin-solid/blob/master/package.json) also include `babel-preset-solid` in _dependencies_.

### Expected:
`babel-preset-solid` is removed from _Installation_ section or it's moved from _dependencies_ to _peerDependencies_ (same as `vite` and `vite-plugin-solid`).
In my opinion, it should be in _peerDependencies_.

**Comment by ryansolid** [comment]
Thanks. It's always been packaged as a dependency as it is required for bundling and redundant outside of that. I'm not sure if I want to reverse that at the moment but we can definitely clean up the readme.
