### ISSUE TITLE
vite-plugin-solid after 2.6.1 vitest not working

### ISSUE THREAD

**Issue by sysmat** [solidjs/vite-plugin-solid#93]
- after update **vite-plugin-solid: 2.5.0 -> 2.6.1**, I get error in tests
- "vitest": "^0.29.2"
- error:

```
TypeError: Cannot read properties of undefined (reading 'solid-refresh')
 ❯ $$refreshESM ../../../../../../../@solid-refresh:243:43
 ❯ Module._$$refresh ../../../../../../../@solid-refresh:273:13
 ❯ src/shared/Error.tsx:10:22
      8| };
      9| 
     10| export default Error;

```

**Comment by sysmat** [comment]
- node_modules/solid-refresh/

```
"name": "solid-refresh",
  "type": "module",
  "description": "Universal HMR for SolidJS",
  "author": "Ryan Carniato",
  "license": "MIT",
  "version": "0.5.0",
  "homepage": "https://github.com/solidjs/solid-refresh#readme",
  "repository": {
    "type": "git",
    "url": "https://github.com/solidjs/solid-refresh"
  },
```

**Comment by ryansolid** [comment]
Hey @lxsmnsyc or @atk, any idea what could be causing this?

**Comment by lxsmnsyc** [comment]
@ryansolid this is a `solid-refresh` bug, more specifically `import.meta.hot.data` not existing in Vitest (for some reason). I'm pushing a fix now

**Comment by sysmat** [comment]
solid-refresh is peer from vite-plugin-solid, so in vite-plugin-solid should be bumped and published

npm list solid-refresh
└─┬ vite-plugin-solid@2.6.1
  └── solid-refresh@0.5.0

**Comment by sysmat** [comment]
Any plan to fix it?

**Comment by lxsmnsyc** [comment]
@sysmat You can re-install the plugin. I believe it should pull the new version of solid-refresh.

**Comment by sysmat** [comment]
@lxsmnsyc re install solved it
