### ISSUE TITLE
Regressions: Bad svg parsing, `TypeError: Cannot read properties of null (reading firstChild/appendChild)`

### ISSUE THREAD

**Issue by vchirikov** [solidjs/vite-plugin-solid#98]
Hi, recently I updated solid-js + vite-plugin-solid and ran into the issue, one of my tests started to produce error: `TypeError: Cannot read properties of null (reading 'firstChild')`

![image](https://user-images.githubusercontent.com/40987940/230799931-454337bb-9ede-4b0f-a9d6-a058ee596b43.png)

```diff
- vite-plugin-solid 2.5.0
+ vite-plugin-solid 2.7.0
```
On 2.5.0 I can't reproduce this.

Repro is big, the test can be found in https://github.com/vchirikov/vite-plugin-ssr-solidjs-blog-example

I tried to create minimal repro - https://github.com/vchirikov/vite-plugin-solid-repro but I ended with another error message (although it's similar):

`TypeError: Cannot read properties of null (reading 'appendChild')`

![image](https://user-images.githubusercontent.com/40987940/230800080-66c84582-0026-493e-8749-733818ea8c2b.png)

Without [this svg part](https://github.com/vchirikov/vite-plugin-solid-repro/blob/c8ec06540336101a32e01455d9d53c5fe7b36d80/tests/repro.tests.tsx#L21-L23
) it works fine on both repositories.

So I think something wrong with svg/path parsing. I didn't find similar issues except recent https://github.com/solidjs/solid/issues/1663 but I'm already on latest `babel-plugin-jsx-dom-expressions` at the moment - `0.36.9`. 

@ryansolid could you check this?

**Comment by ryansolid** [comment]
Thanks for reporting. It works fine in the browser just not in the test environment. There seems to be several issues in the test environment with this that aren't present in chrome or firefox. I think I'm just going to give a way to disable the template shortening. But unfortunate there is a difference between browser and this environment. Maybe we can submit an issue against it but for now I say we disable it in the test setup. 

@atk this is probably relevant. Not sure how to best set it up so the testing DOM environment doesn't break. In any case I will add the config option to dom-expressions.

**Comment by atk** [comment]
I'll have a look.

**Comment by ryansolid** [comment]
I haven't released it yet. I might just opt in for the safer transform anyway. But just something to be aware of.

**Comment by atk** [comment]
This only appears in happy-dom, and not in jsdom, but if it is not urgent, I'll put it further down on my TODO list.

**Comment by vchirikov** [comment]
Looks like fixed on happy-dom side, can't repro with
```yaml
"happy-dom": "^9.10.9",
"vite-plugin-solid": "^2.7.0",
"solid-js": "^1.7.5",
```

**Comment by ryansolid** [comment]
I actually backtracked on Solid. HappyDOM was one example.. I'm sure there would be others.
