### ISSUE TITLE
Could a Solid template be added to Vite?

### ISSUE THREAD

**Issue by rodrigocfd** [solidjs/vite-plugin-solid#99]
Vite, as of v4.3.8, only has [these templates](https://vitejs.dev/guide/#trying-vite-online):

* vanilla;
* Vue;
* React;
* Preact;
* Lit;
* Svelte.

These are the available options of `npm create vite@latest`.

What can be done to add **Solid** to the list?

**Comment by ravenclaw900** [comment]
Solid was added in Vite 4.4.0.

**Comment by rodrigocfd** [comment]
@ravenclaw900 Indeed, it's here now:

* https://vitejs.dev/guide/#trying-vite-online
